name: 'App - Managed Environments'

parameters:
  - name: staticValidation
    displayName: Execute static validation
    type: boolean
    default: true
  - name: deploymentValidation
    displayName: Execute deployment validation
    type: boolean
    default: true
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.app.managedenvironments.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/modules/app/managed-environments/*'
      - '/utilities/pipelines/*'
    exclude:
      - '/utilities/pipelines/deploymentRemoval/*'
      - '/**/*.md'

variables:
  - template: '../../settings.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/modules/app/managed-environments'

stages:
  - template: /.azuredevops/pipelineTemplates/stages.module.yml
    parameters:
      staticValidation: '${{ parameters.staticValidation }}'
      deploymentValidation: '${{ parameters.deploymentValidation }}'
      removeDeployment: '${{ parameters.removeDeployment }}'
      prerelease: '${{ parameters.prerelease }}'
