name: 'AppConfiguration - ConfigurationStores'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.appconfiguration.configurationstores.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/modules/Microsoft.AppConfiguration/configurationStores/*'
      - '/modules/.global/global.module.tests.ps1'
      - '/utilities/pipelines/*'
    exclude:
      - '/utilities/pipelines/dependencies/*'
      - '/**/*.md'

variables:
  - template: '../../global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/modules/Microsoft.AppConfiguration/configurationStores'

stages:
  - template: /.azuredevops/pipelineTemplates/stages.module.yml
    parameters:
      removeDeployment: '${{ parameters.removeDeployment }}'
      prerelease: '${{ parameters.prerelease }}'
      templateFilePath: '$(modulePath)/deploy.bicep'
