name: 'Web - HostingEnvironments'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.web.hostingenvironments.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/arm/Microsoft.Web/hostingEnvironments/*'
      - '/arm/.global/global.module.tests.ps1'
    exclude:
      - '/**/*.md'

variables:
  - template: '../../global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/arm/Microsoft.Web/hostingEnvironments'

stages:
  - stage: Validation
    displayName: Static validation
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModulePester.yml

  - stage: Deployment
    displayName: Deployment validation
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
        parameters:
          removeDeployment: '${{ parameters.removeDeployment }}'
          deploymentBlocks:
            - path: $(modulePath)/.deploymentTests/asev2.parameters.json
            - path: $(modulePath)/.deploymentTests/asev3.parameters.json
          defaultJobTimeoutInMinutes: 180

  - stage: Publishing
    displayName: Publishing
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('${{ parameters.prerelease }}', 'true')))
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.publishModule.yml
