name: 'HealthBot: Healthbots'

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        description: 'Remove deployed module'
        required: false
        default: 'true'
      versioningOption:
        description: 'The mode to handle the version increments [major|minor|patch|custom]'
        required: false
        default: 'patch'
      customVersion:
        description: 'The version to enforce if [versionOption] is set to [custom]'
        required: false
        default: '0.0.1'
  push:
    branches:
      - main
    paths:
      - '.github/actions/templates/**'
      - '.github/workflows/ms.healthbot.healthbots.yml'
      - 'arm/Microsoft.HealthBot/healthBots/**'
      - '!arm/Microsoft.HealthBot/healthBots/readme.md'

env:
  moduleName: 'healthBots'
  modulePath: 'arm/Microsoft.HealthBot/healthBots'
  workflowPath: '.github/workflows/ms.healthbot.healthbots.yml'
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_MGMTGROUP_ID: ${{ secrets.ARM_MGMTGROUP_ID }}

jobs:
  ############################
  #   SET INPUT PARAMETERS   #
  ############################
  job_set_workflow_param:
    runs-on: ubuntu-20.04
    name: 'Set input parameters to output variables'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Set input parameters'
        id: get-workflow-param
        uses: ./.github/actions/templates/getWorkflowInput
        with:
          workflowPath: '${{ env.workflowPath}}'
    outputs:
      removeDeployment: ${{ steps.get-workflow-param.outputs.removeDeployment }}
      versioningOption: ${{ steps.get-workflow-param.outputs.versioningOption }}
      customVersion: ${{ steps.get-workflow-param.outputs.customVersion }}

  ##################
  #   UNIT TESTS   #
  ##################
  # Global tests
  # ------------
  job_tests_module_global:
    runs-on: ubuntu-20.04
    name: 'Run global module tests'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Test module'
        uses: ./.github/actions/templates/validateModuleGeneral
        with:
          modulePath: '${{ env.modulePath }}'
          moduleName: '${{ env.moduleName}}'

  # Global API tests
  # ----------------
  job_tests_module_global_api:
    runs-on: ubuntu-20.04
    name: 'Run global API module tests'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Test module'
        uses: ./.github/actions/templates/validateModuleApis
        with:
          modulePath: '${{ env.modulePath }}'
          moduleName: '${{ env.moduleName}}'

  # Validate deployment module tests
  # --------------------------------
  job_tests_module_deploy_validate:
    runs-on: ubuntu-20.04
    name: 'Run deployment validation module tests'
    strategy:
      fail-fast: false
      matrix:
        parameterFilePaths: ['parameters.json']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set environment variables
        uses: deep-mm/set-variables@v1.0
        with:
          # Name of variable file
          variableFileName: 'variables.module' # Don't write .json here
      - name: 'Test module'
        uses: ./.github/actions/templates/validateModuleDeploy
        with:
          templateFilePath: '${{ env.modulePath }}/deploy.bicep'
          parameterFilePath: '${{ env.modulePath }}/parameters/${{ matrix.parameterFilePaths }}'
          location: '${{ env.defaultLocation }}'
          resourceGroupName: '${{ env.resourceGroupName }}'
          subscriptionId: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
          managementGroupId: '${{ secrets.ARM_MGMTGROUP_ID }}'

  ####################
  #   DEPLOY TESTS   #
  ####################
  job_deploy_module:
    runs-on: ubuntu-20.04
    name: 'Deploy module'
    needs:
      - job_set_workflow_param
      - job_tests_module_global
      - job_tests_module_global_api
      - job_tests_module_deploy_validate
    strategy:
      fail-fast: false
      matrix:
        parameterFilePaths: ['parameters.json']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set environment variables
        uses: deep-mm/set-variables@v1.0
        with:
          # Name of variable file
          variableFileName: 'variables.module' # Don't write .json here
      - name: 'Deploy module'
        uses: ./.github/actions/templates/deployModule
        with:
          moduleName: '${{ env.moduleName }}'
          templateFilePath: '${{ env.modulePath }}/deploy.bicep'
          parameterFilePath: '${{ env.modulePath }}/parameters/${{ matrix.parameterFilePaths }}'
          location: '${{ env.defaultLocation }}'
          resourceGroupName: '${{ env.resourceGroupName }}'
          subscriptionId: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
          managementGroupId: '${{ secrets.ARM_MGMTGROUP_ID }}'
          removeDeployment: '${{ needs.job_set_workflow_param.outputs.removeDeployment }}'

  ###############
  #   PUBLISH   #
  ###############
  job_publish_module:
    name: 'Publish module'
    if: contains(fromJson('["refs/heads/main", "refs/heads/master"]'), github.ref)
    runs-on: ubuntu-20.04
    needs:
      - job_set_workflow_param
      - job_deploy_module
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set environment variables
        uses: deep-mm/set-variables@v1.0
        with:
          # Name of variable file
          variableFileName: 'variables.module' # Don't write .json here
      - name: 'Publish module'
        uses: ./.github/actions/templates/publishModule
        with:
          templateFilePath: '${{ env.modulePath }}/deploy.bicep'
          componentTemplateSpecRGName: '${{ env.componentTemplateSpecRGName }}'
          componentTemplateSpecRGLocation: '${{ env.componentTemplateSpecRGLocation }}'
          componentTemplateSpecName: '${{ env.moduleName }}'
          componentTemplateSpecDescription: '${{ env.componentTemplateSpecDescription }}'
          publishToTemplateSpec: '${{ env.publishToTemplateSpec }}'
          versioningOption: '${{ needs.job_set_workflow_param.outputs.versioningOption }}'
          customVersion: '${{ needs.job_set_workflow_param.outputs.customVersion }}'

  ##############
  #   REMOVE   #
  ##############
  job_remove_module:
    runs-on: ubuntu-20.04
    name: 'Remove module'
    if: ${{ always() && !cancelled() && needs.job_set_workflow_param.outputs.removeDeployment == 'true' && (contains(needs.*.result, 'success') || contains(needs.*.result, 'failure')) }}
    needs:
      - job_deploy_module
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set environment variables
        uses: deep-mm/set-variables@v1.0
        with:
          # Name of variable file
          variableFileName: 'variables.module' # Don't write .json here
      - name: 'Remove module'
        uses: ./.github/actions/templates/removeModule
        with:
          moduleName: '${{ env.moduleName }}'
          templateFilePath: '${{ env.modulePath }}/deploy.bicep'
          resourceGroupName: '${{ env.resourceGroupName }}'
