name: '.Platform: Manage issues for failing pipelines'

on:
  schedule:
    - cron: '30 5 * * *' # Every day at 5:30 am

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Manage issues
        shell: pwsh
        run: |
          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'manageIssueForFailingPipelines' 'Set-IssueForWorkflow.ps1')

          $functionInput = @{
            Repo              = "${{ github.repository_owner }}/${{ github.event.repository.name }}"
            LimitNumberOfRuns = 500
            LimitInDays       = 2
            IgnoreWorkflows   = @('AAD - DomainServices')
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Set-IssueForWorkflow @functionInput -Verbose # -WhatIf
