name: '.Platform: Broken Links Check'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - users/erikag/brokenlinks
    # paths:
    #   - '**/*.md'

jobs:
  build:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Check Broken Links
        if: always()
        id: checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: --verbose --no-progress **/*.md --accept 200,201,403,429,401 --exclude-file .lycheeignore
          format: json
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Publish Results
      #   if: always()
      #   run: exit ${{ steps.checker.outputs.exit_code }}

      - name: Publish Results
        if: always()
        run: echo ${{ steps.checker.outputs }}
